# manual instalation 
# nuxt Devtools
npm i @pinia/nuxt
npm i @pinia-plugin-persistedstate/nuxt
npm i @nuxtjs/axios
npm i alasql 
npm i vue-sweetalert2
npm i @zip.js/zip.js@2.6.40
npm i buffer
npm i file-saver
